### ISSUE TITLE
Publication#send_to_finalizer occasionally failing or not triggering

### ISSUE THREAD

**Issue by ryanfb** [sosol/sosol#151]
See e.g. papyri/sosol#9 papyri/sosol#3

See also #150 - could be an issue with SuckerPunch.

**Comment by jcowey** [comment]
See now also https://github.com/papyri/sosol/issues/13

**Comment by ryanfb** [comment]
Example for a publication in this state:
```
SendToFinalizerJob finished (publication_id: 50602 user_id: )
Actor crashed!
ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: Lock wait timeout exceeded; try restarting transaction: UPDATE `publications` SET `branch` = 'DDbDP_Editorial_Board/finalizing/2016/05/02/O.Frange,_525', `status` = 'finalizing', `updated_at` = '2016-05-02 08:22:33' WHERE `publications`.`
id` = 50776
        arjdbc/jdbc/RubyJdbcConnection.java:663:in `execute_update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.17/lib/arjdbc/jdbc/adapter.rb:503:in `exec_update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `log'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activesupport-3.2.18/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.17/lib/arjdbc/jdbc/adapter.rb:503:in `exec_update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/database_statements.rb:96:in `update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/query_cache.rb:19:in `update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/persistence.rb:359:in `update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/locking/optimistic.rb:68:in `update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/attribute_methods/dirty.rb:74:in `update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/timestamp.rb:71:in `update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/callbacks.rb:272:in `update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:406:in `_run__840570491__update__1020526415__callbacks'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `__run_callback'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:390:in `_run_update_callbacks'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81:in `run_callbacks'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/callbacks.rb:272:in `update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/persistence.rb:348:in `create_or_update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/callbacks.rb:264:in `create_or_update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:461:in `_run__840570491__save__1020526415__callbacks'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `__run_callback'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:390:in `_run_save_callbacks'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81:in `run_callbacks'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/callbacks.rb:264:in `create_or_update'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/persistence.rb:104:in `save!'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/validations.rb:56:in `save!'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/transactions.rb:264:in `save!'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/transactions.rb:313:in `with_transaction_returning_status'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/transactions.rb:208:in `transaction'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/transactions.rb:264:in `save!'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/app/models/publication.rb:517:in `change_status'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/transactions.rb:208:in `transaction'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/transactions.rb:250:in `transaction'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/app/models/publication.rb:511:in `change_status'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/app/models/publication.rb:795:in `send_to_finalizer'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/app/jobs/send_to_finalizer_job.rb:14:in `perform'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/base.rb:77:in `yield_with_lock'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/base.rb:65:in `yield_with_lock_and_timeout'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/base.rb:48:in `with_advisory_lock_if_needed'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/concern.rb:16:in `with_advisory_lock_result'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/concern.rb:10:in `with_advisory_lock'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/concern.rb:6:in `with_advisory_lock'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/app/jobs/send_to_finalizer_job.rb:12:in `perform'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/locking/pessimistic.rb:72:in `with_lock'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/transactions.rb:208:in `transaction'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/transactions.rb:250:in `transaction'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/locking/pessimistic.rb:70:in `with_lock'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/app/jobs/send_to_finalizer_job.rb:11:in `perform'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/app/jobs/send_to_finalizer_job.rb:9:in `perform'
        org/jruby/RubyKernel.java:1930:in `public_send'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `dispatch'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `task'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `task'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `initialize'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `create'
        (celluloid):0:in `remote procedure call'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:12:in `_send_'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:45:in `_send_'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:193:in `method_missing'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `dispatch'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `task'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `task'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `initialize'
        /usr/local/tomcat-sosol/webapps/editor/WEB-INF/gems/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `create'
** [Airbrake] Success: Net::HTTPOK
** [Airbrake] Environment Info: [Ruby: 1.9.3] [Rails: 3.2.18] [Env: production]
** [Airbrake] Response from Airbrake:
UUID: 1676659645569119392
URL:  https://airbrake.io/locate/1676659645569119392
```

**Comment by ryanfb** [comment]
For this example, the SendToFinalizerJob for 50602 times out trying to get a lock on 50776 (the finalizer copy it created) inside the transaction against it when doing `change_status('finalizing')`.
```
app/jobs/send_to_finalizer_job.rb:14:in `perform'
app/models/publication.rb:795:in `send_to_finalizer'
app/models/publication.rb:511:in `change_status'
app/models/publication.rb:517:in `change_status'
```

**Comment by ryanfb** [comment]
Closing with current deployed production code until we have a concrete example of this happening again. Appears to be fixed by fb75393.

**Comment by ryanfb** [comment]
From papyri/sosol#26 we have an instance of this happening again, only now it's just due to the number of "lock wait timeout" retries being exceeded. Maybe we should both increase the number of retries, *and* set/increase the production timeout in `config/database.yml` (*and* potentially increase the timeout in [MySQL itself](http://stackoverflow.com/a/24273965))?

**Comment by ryanfb** [comment]
I've set `wait_timeout=28800` in the production `/etc/my.conf`, and restarted the server. Let's see if that persists and fixes the issue.
